attention_head_size: 4
categorical_groups: {}
dropout: 0.2
embedding_labels:
  fuel_type:
    petrol: 0
embedding_paddings: []
embedding_sizes:
  fuel_type: !!python/tuple
  - 1
  - 1
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 64
learning_rate: 0.005
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 90
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
  center: true
  eps: 1.0e-08
  groups:
  - fuel_type
  method: standard
  missing_:
    center: 170.12380953380952
    scale: 151.1833098615034
  norm_: !!python/object:pandas.core.frame.DataFrame
    _flags:
      allows_duplicate_labels: true
    _metadata: []
    _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
    - !!python/tuple
      - !!python/object/apply:pandas._libs.internals._unpickle_block
        - !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 2
            - 1
          - !!python/object/apply:numpy.dtype
            args:
            - f8
            - false
            - true
            state: !!python/tuple
            - 3
            - <
            - null
            - null
            - null
            - -1
            - -1
            - 0
          - false
          - !!binary |
            o1RpP/ZDZUAghqSs3eViQA==
        - !!python/object/apply:builtins.slice
          - 0
          - 2
          - 1
        - 2
    - - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.base.Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
            - !!python/object/apply:numpy.dtype
              args:
              - O8
              - false
              - true
              state: !!python/tuple
              - 3
              - '|'
              - null
              - null
              - null
              - -1
              - -1
              - 63
            - false
            - - center
              - scale
          name: null
      - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.numeric.Int64Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 1
            - !!python/object/apply:numpy.dtype
              args:
              - i8
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              AAAAAAAAAAA=
          name: fuel_type
    _typ: dataframe
    attrs: {}
  scale_by_group: false
  transformation: softplus
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- fuel_type
static_reals:
- encoder_length
- target_center
- target_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- time_idx
- relative_time_idx
time_varying_reals_encoder:
- time_idx
- relative_time_idx
- target
- Crude_Oil_Price
- Year
- Month
- Quarter
- DayOfYear
- Petrol_Lag1
- Diesel_Lag1
- Crude_Lag1
- Crude_MA7
- Petrol_MA7
- Diesel_MA7
- 'central_bank_total_assets '
- currency_in_circulation
- 'gov_deposits_with_cb '
- srr_commercial_bank_deposits
- reserve_money
- narrow_money_m1
- broad_money_m2
- broad_money_m2b
- quasi_money_public
- net_foreign_assets
- credit_to_government_net
- ' credit_to_public_corporations'
- credit_to_private_sector
- total_domestic_credit
- broad_money_m4
- net_credit_to_gov_central_bank
- net_credit_to_gov_commercial_total
- net_credit_to_gov_commercial_dbu
- net_credit_to_gov_commercial_obu
- credit_to_sobes_dbu
- credit_to_sobes_obu
- credit_to_private_dbu
- credit_to_private_obu
- m2b_other_items_net
- nfa_monetary_authorities
- nfa_commercial_banks_total
- nfa_commercial_banks_dbu
- nfa_commercial_banks_obu
- reserve_money_yoy_pct
- narrow_money_m1_yoy_pct
- 'broad_money_m2_yoy_pct '
- broad_money_m2b_yoy_pct
- 'money_supply_foreign_assets_yoy_pct '
- nfa_monetary_authorities_yoy_pct
- 'nfa_commercial_banks_total_yoy_pct '
- nfa_commercial_banks_dbu_yoy_pct
- nfa_commercial_banks_obu_yoy_pct
- 'net_domestic_assets_yoy_pct '
- net_credit_to_gov_yoy_pct
- net_credit_to_gov_cb_yoy_pct
- net_credit_to_gov_commercial_total_yoy_pct
- net_credit_to_gov_commercial_dbu_yoy_pct
- net_credit_to_gov_commercial_obu_yoy_pct
- credit_to_public_corporations_yoy_pct
- credit_to_sobes_dbu_yoy_pct
- credit_to_sobes_obu_yoy_pct
- credit_to_private_sector_yoy_pct
- credit_to_private_dbu_yoy_pct
- credit_to_private_obu_yoy_pct
- m2b_other_items_net_yoy_pct
- USD_LKR
- annual_cpi_inflation_rate
- policy_rate
- GDP_growth_imports
- consumerprice_inflation
- budget_surplus
- treasury_bonds
weight_decay: 0.0
x_categoricals:
- fuel_type
x_reals:
- encoder_length
- target_center
- target_scale
- time_idx
- relative_time_idx
- target
- Crude_Oil_Price
- Year
- Month
- Quarter
- DayOfYear
- Petrol_Lag1
- Diesel_Lag1
- Crude_Lag1
- Crude_MA7
- Petrol_MA7
- Diesel_MA7
- 'central_bank_total_assets '
- currency_in_circulation
- 'gov_deposits_with_cb '
- srr_commercial_bank_deposits
- reserve_money
- narrow_money_m1
- broad_money_m2
- broad_money_m2b
- quasi_money_public
- net_foreign_assets
- credit_to_government_net
- ' credit_to_public_corporations'
- credit_to_private_sector
- total_domestic_credit
- broad_money_m4
- net_credit_to_gov_central_bank
- net_credit_to_gov_commercial_total
- net_credit_to_gov_commercial_dbu
- net_credit_to_gov_commercial_obu
- credit_to_sobes_dbu
- credit_to_sobes_obu
- credit_to_private_dbu
- credit_to_private_obu
- m2b_other_items_net
- nfa_monetary_authorities
- nfa_commercial_banks_total
- nfa_commercial_banks_dbu
- nfa_commercial_banks_obu
- reserve_money_yoy_pct
- narrow_money_m1_yoy_pct
- 'broad_money_m2_yoy_pct '
- broad_money_m2b_yoy_pct
- 'money_supply_foreign_assets_yoy_pct '
- nfa_monetary_authorities_yoy_pct
- 'nfa_commercial_banks_total_yoy_pct '
- nfa_commercial_banks_dbu_yoy_pct
- nfa_commercial_banks_obu_yoy_pct
- 'net_domestic_assets_yoy_pct '
- net_credit_to_gov_yoy_pct
- net_credit_to_gov_cb_yoy_pct
- net_credit_to_gov_commercial_total_yoy_pct
- net_credit_to_gov_commercial_dbu_yoy_pct
- net_credit_to_gov_commercial_obu_yoy_pct
- credit_to_public_corporations_yoy_pct
- credit_to_sobes_dbu_yoy_pct
- credit_to_sobes_obu_yoy_pct
- credit_to_private_sector_yoy_pct
- credit_to_private_dbu_yoy_pct
- credit_to_private_obu_yoy_pct
- m2b_other_items_net_yoy_pct
- USD_LKR
- annual_cpi_inflation_rate
- policy_rate
- GDP_growth_imports
- consumerprice_inflation
- budget_surplus
- treasury_bonds
