embeddings {
  tensor_name: "fuel_type:00041"
  metadata_path: "00041/fuel_type/metadata.tsv"
  tensor_path: "00041/fuel_type/tensors.tsv"
}
embeddings {
  tensor_name: "fuel_type:00041"
  metadata_path: "00041/fuel_type/metadata.tsv"
  tensor_path: "00041/fuel_type/tensors.tsv"
}
