# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project to the container
COPY . .

# Expose the port that Flask will run on (default is 5000)
EXPOSE 5000

# Set the environment variable to tell Flask to run in production mode
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

# Run the Flask application when the container starts
CMD ["flask", "run", "--host=0.0.0.0"]
