attention_head_size: 4
categorical_groups: {}
dropout: 0.2
embedding_labels:
  fuel_type:
    petrol: 0
embedding_paddings: []
embedding_sizes:
  fuel_type: !!python/tuple
  - 1
  - 1
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 64
learning_rate: 0.004
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
max_encoder_length: 30
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADYyODA0MDYwNDhxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAA2MjgwNDA2
      MDQ4cQFhLgEAAAAAAAAAAAAOQg==
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  eps: 1.0e-08
  max_length: null
  method: standard
  scale_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADU5Mjk0MTUwODhxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAA1OTI5NDE1
      MDg4cQFhLgEAAAAAAAAAd8wrMg==
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- fuel_type
static_reals:
- encoder_length
- petrol_price_center
- petrol_price_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- time_idx
- usd_lkr
- month
- reserve_money
- reserve_money_yoy_pct
- annual_cpi_inflation_rate
- gdp_growth_imports
- consumerprice_inflation
- relative_time_idx
time_varying_reals_encoder:
- time_idx
- usd_lkr
- month
- reserve_money
- reserve_money_yoy_pct
- annual_cpi_inflation_rate
- gdp_growth_imports
- consumerprice_inflation
- relative_time_idx
- petrol_price
weight_decay: 0.0
x_categoricals:
- fuel_type
x_reals:
- encoder_length
- petrol_price_center
- petrol_price_scale
- time_idx
- usd_lkr
- month
- reserve_money
- reserve_money_yoy_pct
- annual_cpi_inflation_rate
- gdp_growth_imports
- consumerprice_inflation
- relative_time_idx
- petrol_price
